### ISSUE TITLE
Skills should move the unit to in front of the user's target (and facing it) depending on the skill

### ISSUE THREAD

**Issue by vitorkei** [Detril/Water-Insignia#9]

**Comment by AndreMoukarzel** [comment]
Acho q tirando quando a skill é auto-aplicada, o personagem sempre deveria ficar de frente com o adversário.

**Comment by vitorkei** [comment]
Attacking an allied unit moves the unit to behind the target just like the basic attack
If the skill is melee-type (not necessarily physical), the user moves to in front of the target; else, the unit only takes a step forward
